"""
GOAL1-01: Dating Pool Monitor & Relocation Trigger

Monitors dating app performance and alerts when local dating pool is exhausted.
Provides escalating alerts (Yellow/Red/Critical) and actionable relocation triggers.

TASK-051: Upgraded to use new Activities API endpoints (US-133, US-135, US-145)
- US-133: Multi-type query in single call
- US-135: Server-side daily aggregation
- US-145: Named measurements (robust kind.name matching)

Dependencies: Activities API share token
Goal: GOAL-1 (Find high-quality long-term partner)
"""

import sqlite3
import json
import requests
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
from enum import Enum

# Activities API configuration
SHARE_TOKEN = "90207c4ed3a54ea4948f29b88b6522dd"  # Updated share token (March 2026)
BASE_URL = "https://xznxeho9da.execute-api.eu-central-1.amazonaws.com"


class PoolStatus(Enum):
    """Dating pool health status with escalating severity."""
    HEALTHY = "HEALTHY"
    THINNING = "THINNING"     # Yellow alert
    DEPLETED = "DEPLETED"      # Red alert
    CRITICAL = "CRITICAL"      # Critical alert (+ location time)


@dataclass
class DatingMetrics:
    """Dating app metrics for a time period."""
    total_swipes: int
    right_swipes: int
    left_swipes: int
    matches: int
    conversations_started: int
    dates_scheduled: int
    match_rate: float  # matches / right_swipes
    period_days: int
    location: Optional[str] = None


@dataclass
class PoolAlert:
    """Alert generated by dating pool monitor."""
    status: PoolStatus
    severity: str  # "info", "warning", "critical"
    one_liner: str
    data_table: List[Dict[str, any]]
    actions: List[Dict[str, str]]  # [{"text": "...", "url": "..."}]
    details: Dict[str, any]


class DatingPoolMonitor:
    """
    Monitors dating app activity and detects pool exhaustion.
    
    TASK-051: Supports both API mode (default, uses US-135) and SQLite mode (for tests).
    Production: use_api=True (server-side aggregation, much faster)
    Tests: use_api=False (local SQLite, allows fixture seeding)
    
    Alert tiers:
    - Yellow: match_rate < 3% for 7 consecutive days AND total_swipes > 50
    - Red: dates_scheduled == 0 for 14 consecutive days AND match_rate < 3%
    - Critical: Red alert + days_in_current_location > 21
    """
    
    def __init__(self, db_path: str = "/var/lib/life-systems/life.db", use_api: bool = True):
        self.db_path = db_path
        self.use_api = use_api  # TASK-051: API mode for production, SQLite for tests
        
        # Alert thresholds
        self.MATCH_RATE_THRESHOLD = 0.03  # 3%
        self.MIN_SWIPES_FOR_ALERT = 40    # Lowered from 50 for practical detection
        self.YELLOW_DAYS = 7
        self.RED_DAYS = 14
        self.CRITICAL_LOCATION_DAYS = 21
    
    def _get_measurement_by_name(self, stats: List[Dict], name: str) -> int:
        """
        Extract measurement value by name from stats response (US-145).
        
        Args:
            stats: List of measurement dictionaries from API
            name: Measurement name to find (e.g., 'swipes', 'matches')
        
        Returns:
            Sum of values for matching measurements, or 0 if not found
        """
        total = 0
        for m in stats:
            kind_name = m.get('kind', {}).get('name', '')
            if kind_name == name:
                value = m.get('value')
                if value is not None:
                    total += int(value)
        return total
    
    def _get_dating_metrics_api(self, days: int, location: Optional[str]) -> DatingMetrics:
        """
        Compute metrics using US-135 daily aggregation API (TASK-051 upgrade).
        
        Much more efficient than raw occurrence processing - server-side aggregation.
        """
        # Calculate date range
        end_date = datetime.now()
        start_date = end_date - timedelta(days=days)
        from_str = start_date.strftime("%Y-%m-%d")
        to_str = end_date.strftime("%Y-%m-%d")
        
        # US-135: Daily aggregation endpoint (single call for bumble + tinder)
        url = f"{BASE_URL}/shared/{SHARE_TOKEN}/stats/daily"
        params = {
            "from": from_str,
            "to": to_str,
            "types": "bumble,tinder"  # US-133: Multi-type query
        }
        
        try:
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()
            daily_stats = response.json()
        except Exception as e:
            # Fallback to zero metrics on API failure
            return DatingMetrics(
                total_swipes=0,
                right_swipes=0,
                left_swipes=0,
                matches=0,
                conversations_started=0,
                dates_scheduled=0,
                match_rate=0.0,
                period_days=days,
                location=location
            )
        
        # Aggregate metrics across all days and types
        # US-145: Named measurements - match by kind.name (robust)
        total_swipes = 0
        right_swipes = 0
        left_swipes = 0
        matches = 0
        conversations_started = 0
        dates_scheduled = 0
        
        for day_entry in daily_stats:
            # Skip if location filter doesn't match (if location filtering requested)
            # Note: location filtering would require fetching raw occurrences
            # For now, we aggregate all data regardless of location
            # TODO: Add location filtering support when API supports it
            
            measurements = day_entry.get('measurements', [])
            
            # US-145: Match measurements by kind.name, not positional index
            total_swipes += self._get_measurement_by_name(measurements, 'swipes')
            right_swipes += self._get_measurement_by_name(measurements, 'right')
            right_swipes += self._get_measurement_by_name(measurements, 'rigth')  # Handle typo
            left_swipes += self._get_measurement_by_name(measurements, 'left')
            matches += self._get_measurement_by_name(measurements, 'matches')
            conversations_started += self._get_measurement_by_name(measurements, 'conversations')
            dates_scheduled += self._get_measurement_by_name(measurements, 'dates')
        
        # Calculate match rate
        match_rate = (matches / right_swipes) if right_swipes > 0 else 0.0
        
        return DatingMetrics(
            total_swipes=total_swipes,
            right_swipes=right_swipes,
            left_swipes=left_swipes,
            matches=matches,
            conversations_started=conversations_started,
            dates_scheduled=dates_scheduled,
            match_rate=match_rate,
            period_days=days,
            location=location
        )
    
    def _get_dating_metrics_sqlite(self, days: int, location: Optional[str]) -> DatingMetrics:
        """
        Compute metrics from local SQLite (legacy mode for tests).
        
        TASK-051: This is the old implementation, kept for test compatibility.
        Production should use API mode (use_api=True).
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cutoff_date = (datetime.now() - timedelta(days=days)).isoformat()
        
        query = '''
        SELECT type, occurred_at, note, measurements, tags
        FROM activities
        WHERE type IN ('bumble', 'tinder')
          AND occurred_at >= ?
        ORDER BY occurred_at DESC
        '''
        
        cursor.execute(query, (cutoff_date,))
        activities = cursor.fetchall()
        conn.close()
        
        # Aggregate metrics
        total_swipes = 0
        right_swipes = 0
        left_swipes = 0
        matches = 0
        conversations_started = 0
        dates_scheduled = 0
        
        for activity in activities:
            activity_type, occurred_at, note, measurements_json, tags_json = activity
            
            # Parse location from tags if filtering
            if location:
                tags = json.loads(tags_json) if tags_json else []
                location_tags = [t for t in tags if t.startswith('loc:')]
                if not any(location in t for t in location_tags):
                    continue  # Skip activities not in specified location
            
            # Parse measurements
            if measurements_json:
                measurements = json.loads(measurements_json)
                for m in measurements:
                    unit = m.get('kind', {}).get('unit', '')
                    value = m.get('value', 0)
                    
                    if unit == 'swipes':
                        total_swipes += int(value)
                    elif unit in ('right', 'rigth'):  # Handle typo in data
                        right_swipes += int(value)
                    elif unit == 'left':
                        left_swipes += int(value)
                    elif unit == 'matches':
                        matches += int(value)
                    elif unit == 'conversations':
                        conversations_started += int(value)
                    elif unit == 'dates':
                        dates_scheduled += int(value)
            
            # Extract matches from note if measurement missing
            if note and 'match' in note.lower():
                if 'no match' in note.lower() or '0 match' in note.lower():
                    pass  # Already counted as 0
                # Could add more sophisticated note parsing here
        
        # Calculate match rate
        match_rate = (matches / right_swipes) if right_swipes > 0 else 0.0
        
        return DatingMetrics(
            total_swipes=total_swipes,
            right_swipes=right_swipes,
            left_swipes=left_swipes,
            matches=matches,
            conversations_started=conversations_started,
            dates_scheduled=dates_scheduled,
            match_rate=match_rate,
            period_days=days,
            location=location
        )
    
    def get_dating_metrics(self, days: int = 7, location: Optional[str] = None) -> DatingMetrics:
        """
        Compute dating metrics for the specified time period.
        
        TASK-051 upgrade: Defaults to API mode (US-135 server-side aggregation).
        Falls back to SQLite mode for test compatibility.
        
        Args:
            days: Number of days to look back
            location: Filter by location tag (e.g., 'corralejo', 'madrid')
        
        Returns:
            DatingMetrics object with computed statistics
        """
        if self.use_api:
            return self._get_dating_metrics_api(days, location)
        else:
            return self._get_dating_metrics_sqlite(days, location)
    
    def get_days_in_current_location(self) -> int:
        """
        Calculate days in current location based on location tags in activities.
        
        Returns:
            Number of consecutive days in the most recent location
        """
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
        SELECT occurred_at, tags
        FROM activities
        WHERE tags LIKE '%loc:%'
        ORDER BY occurred_at DESC
        LIMIT 100
        ''')
        
        activities = cursor.fetchall()
        conn.close()
        
        if not activities:
            return 0
        
        # Find most recent location
        for occurred_at, tags_json in activities:
            tags = json.loads(tags_json) if tags_json else []
            location_tags = [t for t in tags if t.startswith('loc:')]
            if location_tags:
                current_location = location_tags[0].replace('loc:', '')
                break
        else:
            return 0  # No location tags found
        
        # Count consecutive days with same location
        days_count = 0
        last_date = None
        
        for occurred_at, tags_json in activities:
            tags = json.loads(tags_json) if tags_json else []
            location_tags = [t for t in tags if t.startswith('loc:')]
            
            if not location_tags:
                continue
            
            location = location_tags[0].replace('loc:', '')
            if location != current_location:
                break  # Different location, stop counting
            
            activity_date = datetime.fromisoformat(occurred_at.replace('Z', '+00:00')).date()
            
            if last_date is None or activity_date != last_date:
                days_count += 1
                last_date = activity_date
        
        return days_count
    
    def generate_alert(self) -> Optional[PoolAlert]:
        """
        Generate dating pool alert based on current metrics.
        
        Returns:
            PoolAlert if any threshold is exceeded, None if pool is healthy
        """
        # Get metrics for 7 and 14 day periods
        metrics_7d = self.get_dating_metrics(days=7)
        metrics_14d = self.get_dating_metrics(days=14)
        days_in_location = self.get_days_in_current_location()
        
        # Determine pool status
        status = PoolStatus.HEALTHY
        severity = "info"
        
        # Critical: Red conditions + location time > 21 days
        if (metrics_14d.dates_scheduled == 0 and 
            metrics_14d.match_rate < self.MATCH_RATE_THRESHOLD and
            metrics_14d.total_swipes > self.MIN_SWIPES_FOR_ALERT and
            days_in_location > self.CRITICAL_LOCATION_DAYS):
            status = PoolStatus.CRITICAL
            severity = "critical"
        
        # Red: No dates scheduled in 14 days + low match rate
        elif (metrics_14d.dates_scheduled == 0 and 
              metrics_14d.match_rate < self.MATCH_RATE_THRESHOLD and
              metrics_14d.total_swipes > self.MIN_SWIPES_FOR_ALERT):
            status = PoolStatus.DEPLETED
            severity = "critical"
        
        # Yellow: Low match rate for 7 days
        elif (metrics_7d.match_rate < self.MATCH_RATE_THRESHOLD and 
              metrics_7d.total_swipes > self.MIN_SWIPES_FOR_ALERT):
            status = PoolStatus.THINNING
            severity = "warning"
        
        if status == PoolStatus.HEALTHY:
            return None  # No alert needed
        
        # Generate alert message
        if status == PoolStatus.CRITICAL:
            one_liner = (f"🚨 CRITICAL: Dating pool exhausted. "
                        f"0 dates in 14 days, {days_in_location} days in same location. "
                        f"Time to relocate.")
        elif status == PoolStatus.DEPLETED:
            one_liner = (f"🔴 Pool depleted: 0 dates in 14 days, "
                        f"{metrics_14d.match_rate:.1%} match rate. "
                        f"Consider relocation or strategy change.")
        else:  # THINNING
            one_liner = (f"⚠️  Pool thinning: {metrics_7d.match_rate:.1%} match rate "
                        f"over 7 days. Monitor closely.")
        
        # Build data table
        data_table = [
            {
                "period": "7 days",
                "swipes": metrics_7d.total_swipes,
                "matches": metrics_7d.matches,
                "match_rate": f"{metrics_7d.match_rate:.1%}",
                "dates": metrics_7d.dates_scheduled
            },
            {
                "period": "14 days",
                "swipes": metrics_14d.total_swipes,
                "matches": metrics_14d.matches,
                "match_rate": f"{metrics_14d.match_rate:.1%}",
                "dates": metrics_14d.dates_scheduled
            }
        ]
        
        # Build action buttons
        actions = []
        if status in (PoolStatus.DEPLETED, PoolStatus.CRITICAL):
            # Get top recommended city from location optimizer
            actions.append({
                "text": "🛫 Search flights to Madrid",
                "url": "https://www.google.com/flights?q=flights+to+madrid"
            })
            actions.append({
                "text": "📊 View city comparison",
                "url": "/api/cities/recommendation"
            })
        
        if status == PoolStatus.THINNING:
            actions.append({
                "text": "💡 Strategy tips",
                "url": "/advisor#dating-strategy"
            })
        
        # Build details dict
        details = {
            "days_in_location": days_in_location,
            "metrics_7d": {
                "total_swipes": metrics_7d.total_swipes,
                "right_swipes": metrics_7d.right_swipes,
                "matches": metrics_7d.matches,
                "match_rate": metrics_7d.match_rate,
                "dates_scheduled": metrics_7d.dates_scheduled
            },
            "metrics_14d": {
                "total_swipes": metrics_14d.total_swipes,
                "right_swipes": metrics_14d.right_swipes,
                "matches": metrics_14d.matches,
                "match_rate": metrics_14d.match_rate,
                "dates_scheduled": metrics_14d.dates_scheduled
            }
        }
        
        return PoolAlert(
            status=status,
            severity=severity,
            one_liner=one_liner,
            data_table=data_table,
            actions=actions,
            details=details
        )
    
    def get_dashboard_card(self) -> Dict:
        """
        Generate dashboard card data for advisor view.
        
        Returns:
            Dictionary with card data suitable for dashboard rendering
        """
        alert = self.generate_alert()
        
        if alert is None:
            # Healthy pool - show positive status
            metrics_7d = self.get_dating_metrics(days=7)
            return {
                "status": "HEALTHY",
                "severity": "info",
                "one_liner": f"✅ Dating pool healthy: {metrics_7d.match_rate:.1%} match rate, {metrics_7d.dates_scheduled} dates scheduled",
                "data_table": [
                    {
                        "period": "7 days",
                        "swipes": metrics_7d.total_swipes,
                        "matches": metrics_7d.matches,
                        "match_rate": f"{metrics_7d.match_rate:.1%}",
                        "dates": metrics_7d.dates_scheduled
                    }
                ],
                "actions": [
                    {"text": "📊 View trends", "url": "/advisor#dating-trends"}
                ]
            }
        
        return {
            "status": alert.status.value,
            "severity": alert.severity,
            "one_liner": alert.one_liner,
            "data_table": alert.data_table,
            "actions": alert.actions,
            "details": alert.details
        }


def check_pool_status() -> Dict:
    """
    Convenience function for sprint checks.
    
    Returns:
        Dashboard card data
    """
    monitor = DatingPoolMonitor()
    return monitor.get_dashboard_card()


if __name__ == "__main__":
    # CLI testing
    monitor = DatingPoolMonitor()
    card = monitor.get_dashboard_card()
    
    print("Dating Pool Monitor")
    print("=" * 50)
    print(f"Status: {card['status']}")
    print(f"Severity: {card['severity']}")
    print(f"\n{card['one_liner']}")
    print(f"\nMetrics:")
    for row in card['data_table']:
        print(f"  {row}")
    print(f"\nActions:")
    for action in card['actions']:
        print(f"  - {action['text']}: {action['url']}")
